[package]
name = "gmt_dos-clients_mount"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
dos-actors.workspace = true
dos-clients_io.workspace = true
log.workspace = true
mount-ctrl = { version = "2.1.0", package = "gmt_mount-ctrl" }
thiserror.workspace = true

[features]
s8000d002ze60 = ["mount-ctrl/s8000d002ze60"]
s1000d002ze00 = ["mount-ctrl/s1000d002ze00"]
s1000d002ze30 = ["mount-ctrl/s1000d002ze30"]
s1000d002ze60 = ["mount-ctrl/s1000d002ze60"]
s8000d0005 = ["mount-ctrl/s8000d0005"]
s8000d002ze00 = ["mount-ctrl/s8000d002ze00"]
s8000d002ze30 = ["mount-ctrl/s8000d002ze30"]

[dev-dependencies]
dos-clients_arrow = { version = "0.2.0", package = "gmt_dos-clients_arrow" }
skyangle = "0.2.2"
tokio = { version = "1.24.1", features = ["full"] }
anyhow = "1.0.68"
fem.workspace = true
lom = { version = "1.1.0", package = "gmt-lom", features = ["main"] }
