[package]
name = "gmt_dos-clients_mount"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
dos-actors = { workspace = true }
dos-clients_io = { version = "0.1.0", path = "../io", package = "gmt_dos-clients_io" }
log = { workspace = true }
mount-ctrl = { version = "2.1.0", package = "gmt_mount-ctrl" }
thiserror = { workspace = true }

[features]
s8000d002ze60 = ["mount-ctrl/s8000d002ze60"]
s1000d002ze00 = ["mount-ctrl/s1000d002ze00"]
s1000d002ze30 = ["mount-ctrl/s1000d002ze30"]
s1000d002ze60 = ["mount-ctrl/s1000d002ze60"]
s8000d0005 = ["mount-ctrl/s8000d0005"]
s8000d002ze00 = ["mount-ctrl/s8000d002ze00"]
s8000d002ze30 = ["mount-ctrl/s8000d002ze30"]
