[package]
name = "gmt_dos-clients_mount"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gmt_dos-clients = { workspace = true, default-features = false, features = [
    "interface",
] }
gmt_dos-clients_io.workspace = true
gmt_dos-clients_arrow.workspace = true
log.workspace = true
mount-ctrl = { version = "2.1.0", package = "gmt_mount-ctrl" }
thiserror.workspace = true

[features]
s8000d002ze60 = ["mount-ctrl/s8000d002ze60"]
s1000d002ze00 = ["mount-ctrl/s1000d002ze00"]
s1000d002ze30 = ["mount-ctrl/s1000d002ze30"]
s1000d002ze60 = ["mount-ctrl/s1000d002ze60"]
s8000d0005 = ["mount-ctrl/s8000d0005"]
s8000d002ze00 = ["mount-ctrl/s8000d002ze00"]
s8000d002ze30 = ["mount-ctrl/s8000d002ze30"]

[dev-dependencies]
gmt_dos-actors.workspace = true
skyangle = "0.2.2"
tokio = { version = "1.24.1", features = ["full"] }
anyhow = "1.0.68"
gmt-fem.workspace = true
lom = { version = "1.1.0", package = "gmt-lom", features = ["main"] }
gmt_dos-clients_fem.workspace = true
gmt_dos-clients.workspace = true
env_logger = "0.10.0"

[package.metadata.docs.rs]
features = ["s8000d002ze30"]
