[package]
name = "gmt_dos-clients_m1-ctrl"
version = "0.1.0"
edition = "2021"

[dependencies]
center = { version = "0.1.0", package = "gmt_m1-ctrl_center-actuators" }
hardpoints-dynamics = { version = "0.1.0", package = "gmt_m1-ctrl_hardpoints-dynamics" }
outer = { version = "0.1.0", package = "gmt_m1-ctrl_outer-actuators" }
gmt_dos-actors.workspace = true
gmt_dos-actors_interface.workspace = true
gmt_dos-clients.workspace = true
gmt_dos-clients_io.workspace = true
gmt_dos-clients_fem.workspace = true
nalgebra.workspace = true
gmt-fem.workspace = true
anyhow = "1.0.69"

[dev-dependencies]
tokio = "1.25.0"
