[package]
name = "dos-actors"
version = "0.1.0"
edition = "2021"

[dependencies]
flume = "0.10.9"
futures = "0.3.19"
quote = "1.0.14"
syn = "1.0.85"
thiserror = "1.0.30"
paste = "1.0.6"
geotrans = "0.2"
async-trait = "0.1.52"
nalgebra = { version = "0.30.1", optional = true, features = ["serde-serialize"] }
skyangle = "0.1"
anyhow = "1.0.56"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread", "sync", "rt", "time"] }
parse-monitors = { git = "https://github.com/rconan/parse-monitors.git", branch = "main", optional = true}
fem = { version = "0.2.6", package = "gmt-fem" , optional = true}
#mount-ctrl = { version = "0.2" , optional = true}
mount-ctrl = { git = "https://github.com/rconan/mount-ctrl.git", branch = "linear-drv", optional = true}
m1-ctrl = { git = "https://github.com/rconan/m1-ctrl.git", branch = "hf_design", optional = true }
arrow = { version = "10.0.0", optional = true }
parquet = { version = "10.0.0", optional = true }
rand = { version = "0.8.5", optional = true }
rand_distr = { version = "0.4.3", optional = true }
fsm = { git = "https://github.com/rodrigo-romano/m2-ctrl-code.git", branch = "2022-03-update", optional = true }
crseo = { path = "../crseo/", optional = true }
serde-pickle = { version = "1.1.0", optional = true }
lom = { version = "0.1.6", package = "gmt-lom", features = ["apache"], optional = true }
osqp = { version = "0.6.2", optional = true }
humantime = "2.1.0"
chrono = "0.4.19"
linya = "0.2.2"
bincode = "1.3.3"
log = "0.4.16"
uid-derive = { version = "0.1.0", package = "dos-uid-derive" }
uid = { version = "0.1.0", package = "dos-uid"}

[features]
windloads = ["parse-monitors"]
apache-arrow = ["arrow", "parquet"]
ceo = ["crseo", "nalgebra"]
noise = ["rand", "rand_distr"]
sampler = []
feedback = []
full = ["windloads", "apache-arrow", "ceo", "fem", "mount-ctrl", "m1-ctrl", "fsm", "lom"]
dta = []

[dev-dependencies]
anyhow = "1.0.52"
complot = "0.3.2"
rand = "0.8.4"
rand_distr = "0.4.3"
simple_logger = "2.1.0"
structopt = "0.3.26"
tokio-test = "0.4.2"
serde-pickle = "1.1.0"
env_logger = "0.9.0"

[[test]]
name = "zero_mount"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom"]
[[test]]
name = "setpoint_mount"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom"]

[[test]]
name = "zero_mount-m1-rbm"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom", "m1-ctrl"]
[[test]]
name = "setpoint_mount-m1"
required-features = ["fem", "mount-ctrl", "m1-ctrl"]
[[test]]
name = "setpoint_mount-m1-rbm"
required-features = ["fem", "mount-ctrl", "m1-ctrl", "nalgebra"]

[[test]]
name = "zero_mount-m1-m2"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom", "m1-ctrl", "fsm"]
[[test]]
name = "setpoint_mount-m1-m2"
required-features = ["fem", "mount-ctrl", "m1-ctrl", "fsm"]

[[test]]
name = "zero_mount-m1-m2-tt"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom", "m1-ctrl", "fsm", "nalgebra"]
[[test]]
name = "setpoint_mount-m1-m2-tt"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom", "m1-ctrl", "fsm", "ceo"]

[[example]]
name = "batch_fem"
required-features = ["fem", "apache-arrow", "mount-ctrl", "windloads"]
