[package]
name = "gmt_dos-actors"
version = "5.0.4"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2021"
license = "MIT"
description = "Giant Magellan Telescope Dynamic Optical Simulation Actor Model"
repository = "https://github.com/rconan/dos-actors"
documentation = "https://docs.rs/dos-actors"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

[workspace]
members = ["book"]

[workspace.dependencies]
anyhow = "1.0.52"
tokio = "1.15.0"

[dependencies]
flume = "0.10.9"
futures = "0.3.19"
thiserror = "1.0.30"
async-trait = "0.1.52"
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "rt",
    "time",
] }
rand = { version = "0.8.5", optional = true }
rand_distr = { version = "0.4.3", optional = true }
serde-pickle = { version = "1.1.0", optional = true }
humantime = "2.1.0"
chrono = "0.4.19"
linya = "0.3.0"
log = { version = "0.4.16", features = ["release_max_level_info"] }
uid-derive = { version = "1.0.1", path = "uid-derive", package = "dos-uid-derive" }
matio-rs = { version = "0.2.1", optional = true }
nalgebra = { version = "0.31.1", optional = true }
vec_box = "1.0.0"
paris = { version = "1.5.13", features = ["no_logger"] }

[features]
default = ["clients"]
clients = []
noise = ["rand", "rand_distr"]
sampler = []
feedback = []
dta = []

[dev-dependencies]
rand = "0.8.4"
rand_distr = "0.4.3"
simple_logger = "2.1.0"
structopt = "0.3.26"
tokio-test = "0.4.2"
serde-pickle = "1.1.0"
env_logger = "0.9.0"
complot = "0.3.3"
ron = "0.8.0"
anyhow.workspace = true

[[test]]
name = "zero_mount-m1-rbm"
required-features = [
    "fem",
    "mount-ctrl_s1000d002ze30",
    "apache-arrow",
    "lom",
    "m1-ctrl",
]

[[test]]
name = "setpoint_mount-m1"
required-features = ["fem", "mount-ctrl", "m1-ctrl"]

[[test]]
name = "setpoint_mount-m1-rbm"
required-features = ["fem", "mount-ctrl", "m1-ctrl", "nalgebra"]

[[test]]
name = "zero_mount-m1-m2"
required-features = [
    "fem",
    "mount-ctrl",
    "apache-arrow",
    "lom",
    "m1-ctrl",
    "fsm",
]

[[test]]
name = "setpoint_mount-m1-m2"
required-features = ["fem", "mount-ctrl", "m1-ctrl", "fsm"]

[[test]]
name = "setpoint_mount-m1-asm"
required-features = ["fem", "mount-ctrl/s8000d0005", "m1-ctrl", "asm"]

[[test]]
name = "setpoint_mount-m1-asm-pos"
required-features = [
    "fem",
    "mount-ctrl_s8000d0005",
    "m1-ctrl",
    "asm",
    "apache-arrow",
]

[[test]]
name = "zero_mount-m1-m2-tt"
required-features = [
    "fem",
    "mount-ctrl",
    "apache-arrow",
    "lom",
    "m1-ctrl",
    "fsm",
    "nalgebra",
]

[[test]]
name = "setpoint_mount-m1-m2-tt"
required-features = [
    "fem",
    "mount-ctrl",
    "apache-arrow",
    "lom",
    "m1-ctrl",
    "fsm",
    "ceo",
]

[[example]]
name = "wind_loading"
required-features = ["fem", "mount-ctrl", "apache-arrow", "windloads"]
[[example]]
name = "wind_loads"
required-features = ["fem", "apache-arrow", "windloads"]
[[example]]
name = "static_aberration"
required-features = ["ceo", "apache-arrow"]

[package.metadata.docs.rs]
features = ["noise"]
