[package]
name = "dos-actors"
version = "1.0.3"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2021"
license = "MIT"
description = "Giant Magellan Telescope Dynamic Optical Simulation Actor Model"
repository = "https://github.com/rconan/dos-actors"
documentation = "https://docs.rs/dos-actors"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

[dependencies]
flume = "0.10.9"
futures = "0.3.19"
quote = "1.0.14"
syn = "1.0.85"
thiserror = "1.0.30"
paste = "1.0.6"
geotrans = "0.2"
async-trait = "0.1.52"
nalgebra = { version = "0.31", optional = true, features = ["serde-serialize"] }
skyangle = "0.1"
anyhow = "1.0.56"
tokio = { version = "1.15.0", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "rt",
    "time",
] }
parse-monitors = { version = "0.1.0", optional = true }
fem = { version = "0.3.0", package = "gmt-fem", optional = true }
mount-ctrl = { version = "0.3.0", git = "https://github.com/rconan/mount-ctrl.git", branch = "main", optional = true }
m1-ctrl = { version = "0.1.2", optional = true }
arrow = { version = "10.0.0", optional = true }
parquet = { version = "10.0.0", optional = true }
rand = { version = "0.8.5", optional = true }
rand_distr = { version = "0.4.3", optional = true }
fsm = { version = "0.1.0", package = "m2-ctrl", optional = true }
serde-pickle = { version = "1.1.0", optional = true }
lom = { version = "0.1.8", package = "gmt-lom", features = [
    "apache",
], optional = true }
osqp = { version = "0.6.2", optional = true }
humantime = "2.1.0"
chrono = "0.4.19"
linya = "0.2.2"
bincode = "1.3.3"
log = "0.4.16"
uid-derive = { version = "0.3.1", path = "uid-derive", package = "dos-uid-derive" }
uid = { version = "0.1.2", path = "uid", package = "dos-uid" }
matio-rs = { version = "0.1.1", optional = true }
crseo = { version = "0.4.5", optional = true }
serde = { version = "1.0.137", features = ["derive"] }
glob = "0.3.0"

[features]
windloads = ["parse-monitors"]
apache-arrow = ["arrow", "parquet"]
ceo = ["crseo", "nalgebra"]
noise = ["rand", "rand_distr"]
sampler = []
feedback = []
main = [
    "windloads",
    "apache-arrow",
    "ceo",
    "mount-ctrl",
    "m1-ctrl",
    "fsm",
    "lom",
]
dta = []

[dev-dependencies]
anyhow = "1.0.52"
rand = "0.8.4"
rand_distr = "0.4.3"
simple_logger = "2.1.0"
structopt = "0.3.26"
tokio-test = "0.4.2"
serde-pickle = "1.1.0"
env_logger = "0.9.0"
complot = "0.3.3"

[[test]]
name = "zero_mount"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom"]
[[test]]
name = "setpoint_mount"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom"]

[[test]]
name = "zero_mount-m1-rbm"
required-features = ["fem", "mount-ctrl", "apache-arrow", "lom", "m1-ctrl"]
[[test]]
name = "setpoint_mount-m1"
required-features = ["fem", "mount-ctrl", "m1-ctrl"]
[[test]]
name = "setpoint_mount-m1-rbm"
required-features = ["fem", "mount-ctrl", "m1-ctrl", "nalgebra"]

[[test]]
name = "zero_mount-m1-m2"
required-features = [
    "fem",
    "mount-ctrl",
    "apache-arrow",
    "lom",
    "m1-ctrl",
    "fsm",
]
[[test]]
name = "setpoint_mount-m1-m2"
required-features = ["fem", "mount-ctrl", "m1-ctrl", "fsm"]

[[test]]
name = "zero_mount-m1-m2-tt"
required-features = [
    "fem",
    "mount-ctrl",
    "apache-arrow",
    "lom",
    "m1-ctrl",
    "fsm",
    "nalgebra",
]
[[test]]
name = "setpoint_mount-m1-m2-tt"
required-features = [
    "fem",
    "mount-ctrl",
    "apache-arrow",
    "lom",
    "m1-ctrl",
    "fsm",
    "ceo",
]

[[example]]
name = "wind_loading"
required-features = ["fem", "mount-ctrl", "apache-arrow", "windloads"]
[[example]]
name = "wind_loads"
required-features = ["fem", "apache-arrow", "windloads"]
[[example]]
name = "static_aberration"
required-features = ["ceo", "apache-arrow"]

[package.metadata.docs.rs]
features = ["main"]
