[workspace]
members = [
    "actors",
    "actors/uid-derive",
    "clients/windloads",
    "clients/crseo",
    "clients/domeseeing",
    "clients/arrow",
    "clients/mount",
    "clients/io",
    "clients/m1-ctrl",
    "clients/m2-ctrl",
    "clients/fem",
    "clients/crseo/tms",
]

[workspace.package]
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2021"
license = "MIT"
description = "Giant Magellan Telescope Dynamic Optical Simulation Actor's client"
repository = "https://github.com/rconan/dos-actors"
documentation = "https://docs.rs/dos-actors"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

[workspace.dependencies]
gmt_dos-clients = { version = "1.0.0", path = "clients/" }
gmt-fem = { version = "2.0.0", path = "../fem/" }
gmt_dos-actors = { version = "6.0.0", path = "actors/" }
dos-uid-derive = { version = "2.0.0", path = "actors/uid-derive/" }
gmt_dos-clients_io = { version = "1.0.0", path = "clients/io" }
gmt_dos-clients_fem = { version = "0.1.0", path = "clients/fem/" }
gmt_dos-clients_mount = { version = "0.1.1", path = "clients/mount/" }
gmt_dos-clients_m1-ctrl = { version = "0.1.0", path = "clients/m1-ctrl/" }
gmt_dos-clients_arrow = { version = "0.2.2", path = "clients/arrow/" }
gmt_dos-clients_domeseeing = { version = "0.1.0", path = "clients/domeseeing/" }
gmt_dos-clients_crseo = { version = "0.1.0", path = "clients/crseo/" }
log = "0.4.17"
thiserror = "1.0.36"
tokio-test = "0.4.2"
nalgebra = "0.32.1"
tokio = { version = "1.25.0" }
anyhow = "1.0.68"
crseo = { version = "0.4.5", path = "../crseo" }
rayon = "1.6.1"
env_logger = "0.10.0"
matio-rs = { version = "1.3.0" }                                                 #, path = "../../matio-rs" }
skyangle = "0.2.2"
