[package]
name = "gmt_dos-clients_m2-ctrl"
version = "0.1.0"
edition = "2021"

[dependencies]
gmt_m2-ctrl_asm_preshape-filter = "0.1.0"
gmt_m2-ctrl_asm_pid-damping = "0.1.0"
gmt_dos-actors.workspace = true
gmt_dos-clients.workspace = true
gmt_dos-clients_io.workspace = true
gmt_dos-clients_fem = { workspace = true, features = ["asm"] }
gmt-fem.workspace = true
rayon.workspace = true
nalgebra = { workspace = true, features = ["serde", "serde-serialize"] }
log.workspace = true
anyhow.workspace = true
matio-rs.workspace = true
thiserror.workspace = true
bincode = "1.3.3"
serde = { version = "1.0.152", features = ["derive"] }
paste = "1.0.12"

[dev-dependencies]
matio-rs = { workspace = true, features = ["nalgebra"] }
tokio = { workspace = true, features = ["full"] }
env_logger.workspace = true
nanorand = "0.7.0"
