[workspace]
members = ["windloads", "crseo", "domeseeing", "arrow", "mount", "io"]

[workspace.package]
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2021"
license = "MIT"
description = "Giant Magellan Telescope Dynamic Optical Simulation Actor's client"
repository = "https://github.com/rconan/dos-actors"
documentation = "https://docs.rs/dos-actors"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

[workspace.dependencies]
gmt_dos-actors = { version = "5.0.1", path = "../" }
dos-clients_io = { version = "1.0.0", package = "gmt_dos-clients_io" }
log = "0.4.17"
thiserror = "1.0.36"
tokio-test = "0.4.2"
fem = { version = "1.1.0", package = "gmt-fem" }
