[package]
name = "gmt_dos-clients"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["windloads", "crseo", "domeseeing", "arrow", "mount"]

[workspace.dependencies]
dos-actors = { version = "3.0.1", path = "..", package = "gmt_dos-actors" }
log = "0.4.17"
thiserror = "1.0.36"
tokio-test = "0.4.2"
