[package]
name = "gmt_dos-clients"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true

[workspace]
members = [
    "windloads",
    "crseo",
    "domeseeing",
    "arrow",
    "mount",
    "io",
    "m1-ctrl",
    "fem",
    "crseo/tms",
]

[workspace.package]
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2021"
license = "MIT"
description = "Giant Magellan Telescope Dynamic Optical Simulation Actor's client"
repository = "https://github.com/rconan/dos-actors"
documentation = "https://docs.rs/dos-actors"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

[workspace.dependencies]
gmt-fem = { version = "1.2.0" }
gmt_dos-actors = { path = "../" }
gmt_dos-clients = { path = "." }
gmt_dos-clients_io = { path = "io/" }
gmt_dos-clients_fem = { path = "fem/" }
gmt_dos-clients_arrow = { path = "arrow/" }
gmt_dos-clients_domeseeing = { path = "domeseeing/" }
gmt_dos-clients_crseo = { path = "crseo/" }
log = "0.4.17"
thiserror = "1.0.36"
tokio-test = "0.4.2"
nalgebra = "0.31"
tokio = { version = "1.25.0" }
anyhow = "1.0.68"
crseo = { version = "0.4.5", path = "../../crseo" }

[dependencies]
thiserror.workspace = true
rand = { version = "0.8.5", optional = true }
rand_distr = { version = "0.4.3", optional = true }
paris = { version = "1.5.13", optional = true }
log = { workspace = true, optional = true }
dos-uid-derive = { version = "2.0.0", path = "../uid-derive", optional = true }

[features]
default = ["clients"]
clients = ["interface"]
noise = ["rand", "rand_distr"]
interface = ["paris", "log", "dos-uid-derive"]
