[workspace]
members = ["windloads", "crseo", "domeseeing", "arrow", "mount", "io"]

[workspace.package]
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2021"
license = "MIT"
description = "Giant Magellan Telescope Dynamic Optical Simulation Actor's client"
repository = "https://github.com/rconan/dos-actors"
documentation = "https://docs.rs/dos-actors"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

[workspace.dependencies]
dos-actors = { version = "3.0.1", path = "..", package = "gmt_dos-actors" }
dos-clients_io = { version = "0.1.0", path = "io", package = "gmt_dos-clients_io" }
log = "0.4.17"
thiserror = "1.0.36"
tokio-test = "0.4.2"
