[package]
name = "gmt_dos-clients_crseo"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
crseo = { version = "0.4.5" }
domeseeing = { version = "0.1.0", path = "../domeseeing", package = "gmt_dos-clients_domeseeing" }
gmt_dos-actors = { workspace = true }
log = { workspace = true }
nalgebra = "0.31.1"
thiserror = { workspace = true }
dos-clients_io = { workspace = true }

[dev-dependencies]
anyhow = "1.0.65"
arrow = {  package = "gmt_dos-clients_arrow" }
linya = "0.3.0"
skyangle = "0.1.2"
tokio = "1.21.1"
