[package]
name = "gmt_dos-clients_arrow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "10.0.0"
dos-actors = { workspace = true }
log = { workspace = true }
parquet = "10.0.0"
paste = "1.0.9"
thiserror = { workspace = true }
