[package]
name = "gmt_dos-clients_fem"
version = "0.1.0"
edition = "2021"

[dependencies]
gmt_dos-clients = { workspace = true, default-features = false, features = [
    "interface",
] }
gmt_dos-clients_io.workspace = true
gmt-fem.workspace = true
log.workspace = true
rayon = "1.6.1"
nalgebra.workspace = true
num-complex = "0.4.3"
serde-pickle = "1.1.1"
clap = { version = "4.1.1", features = ["derive"], optional = true }
thiserror.workspace = true
serde = { version = "1.0.152", features = ["derive"] }

[features]
fsm = []
asm = []

[[bin]]
name = "cargo-gmt-fem"
path = "src/bin/inspect.rs"
required-features = ["clap"]
