[package]
name = "gmt_dos-clients_io"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
dos-actors = { workspace = true, default-features = false }
