[package]
name = "gmt_dos-clients_io"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "GMT DOS Inputs/Outputs"
documentation = "https://docs.rs/gmt_dos-clients_io"
readme = "../README.md"
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gmt_dos-actors = { workspace = true, default-features = false }
gmt_dos-clients = { workspace = true, package = "gmt_dos-clients", default-features = false, features = [
    "interface",
] }
