[package]
name = "gmt_dos-clients_windloads"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
dos-actors = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
parse-monitors = "0.1.1"
geotrans = "0.2.2"
fem = { version = "0.3.0", package = "gmt-fem", path = "../../../fem", optional = true }
dos-clients_io = { workspace = true }

[features]
default = ["fem"]
asm = ["fem/asm"]
fsm = ["fem/fsm"]
