[package]
name = "gmt_dos-clients_windloads"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gmt_dos-actors.workspace = true
log.workspace = true
thiserror = { workspace = true }
parse-monitors = "0.1.1"
geotrans = "0.2.2"
gmt-fem = { workspace = true, optional = true }
gmt_dos-clients_io = { workspace = true }

[features]
default = ["gmt-fem"]
asm = ["gmt-fem/asm"]
fsm = ["gmt-fem/fsm"]
